def text_node(text, marks=None):

    node = {
        "type": "text",
        "text": str(text)
    }

    if marks:

        node["marks"] = marks

    return node


def paragraph(text):

    return {
        "type": "paragraph",
        "content": [
            text_node(text)
        ]
    }


def heading(text, level=3):

    return {
        "type": "heading",
        "attrs": {
            "level": level
        },
        "content": [
            text_node(text)
        ]
    }


def panel(text, panel_type="info"):

    return {
        "type": "panel",
        "attrs": {
            "panelType": panel_type
        },
        "content": [
            paragraph(text)
        ]
    }


def bullet_list(items):

    clean_items = [
        item.strip()
        for item in items
        if item and item.strip()
    ]

    if not clean_items:

        return None

    return {
        "type": "bulletList",
        "content": [
            {
                "type": "listItem",
                "content": [
                    paragraph(item)
                ]
            }
            for item in clean_items
        ]
    }


def rule():

    return {
        "type": "rule"
    }


def adf_doc(content):

    return {
        "type": "doc",
        "version": 1,
        "content": content
    }


def normalize_lines(value):

    lines = []

    for line in str(value or "").splitlines():

        cleaned_line = line.strip()

        if cleaned_line:

            lines.append(cleaned_line)

    if not lines and value:

        lines.append(str(value))

    return lines


def normalize_bullets(value):

    bullets = []

    for line in normalize_lines(value):

        cleaned_line = (
            line
            .lstrip("-")
            .lstrip("*")
            .strip()
        )

        if cleaned_line:

            bullets.append(cleaned_line)

    return bullets


def section(title, body):

    nodes = [
        heading(title, 3)
    ]

    for line in normalize_lines(body):

        nodes.append(
            paragraph(line)
        )

    return nodes


def build_processing_adf(current_step, completed_steps=None):

    completed_steps = completed_steps or []

    progress_items = [
        f"Done: {step}"
        for step in completed_steps
    ]

    progress_items.append(
        f"In progress: {current_step}"
    )

    return adf_doc([
        heading("AI Analysis", 2),
        panel(
            f"Status: Processing. Current step: {current_step}",
            "info"
        ),
        heading("Progress", 3),
        bullet_list(progress_items)
    ])


def build_failed_adf(error_message):

    return adf_doc([
        heading("AI Analysis Failed", 2),
        panel(
            "Status: Failed. The automation could not complete the AI analysis.",
            "error"
        ),
        heading("Reason", 3),
        paragraph(str(error_message)[:1000])
    ])


def build_ai_summary_adf(
    ai_summary,
    translated_content,
    sentiment,
    comments_summary,
    detected_language
):

    content = [
        heading("AI Issue Summary", 2),
        panel(
            "Status: Complete. Generated by the local Jira AI assistant using ticket details and knowledge base context.",
            "success"
        ),
        rule()
    ]

    content.extend(
        section(
            "Summary",
            ai_summary
        )
    )

    content.extend(
        section(
            "English Translation",
            translated_content
        )
    )

    content.append(
        heading("Signal", 3)
    )

    signal_list = bullet_list([
        f"Sentiment: {sentiment}",
        f"Detected language: {detected_language}"
    ])

    if signal_list:

        content.append(signal_list)

    if comments_summary and comments_summary.strip():

        content.append(
            heading("Comment Summary", 3)
        )

        comment_list = bullet_list(
            normalize_bullets(comments_summary)
        )

        if comment_list:

            content.append(comment_list)

    return adf_doc(content)
